from rl_x.algorithms.algorithm_manager import extract_algorithm_name_from_file, register_algorithm
from trust_region_irl.algorithms.trirl_trpl.flax_full_jit.trirl_trpl import TRIRL_TRPL
from trust_region_irl.algorithms.trirl_trpl.flax_full_jit.default_config import get_config
from trust_region_irl.algorithms.trirl_trpl.flax_full_jit.general_properties import GeneralProperties


TRIRL_TRPL_FLAX_FULL_JIT = extract_algorithm_name_from_file(__file__)
register_algorithm(TRIRL_TRPL_FLAX_FULL_JIT, get_config, TRIRL_TRPL, GeneralProperties)
