from rl_x.algorithms.algorithm_manager import extract_algorithm_name_from_file, register_algorithm
from trust_region_irl.algorithms.trirl_ppo.flax_loco_mjx.trirl_ppo import TRIRL_PPO
from trust_region_irl.algorithms.trirl_ppo.flax_loco_mjx.default_config import get_config
from trust_region_irl.algorithms.trirl_ppo.flax_loco_mjx.general_properties import GeneralProperties


TRIRL_PPO_FLAX_LOCO_MJX = extract_algorithm_name_from_file(__file__)
register_algorithm(TRIRL_PPO_FLAX_LOCO_MJX, get_config, TRIRL_PPO, GeneralProperties)
