from rl_x.environments.environment_manager import extract_environment_name_from_file, register_environment
from trust_region_irl.environments.loco_mjx.create_env import create_env
from trust_region_irl.environments.loco_mjx.default_config import get_config
from trust_region_irl.environments.loco_mjx.general_properties import GeneralProperties


CUSTOM_LOCO_MJX = extract_environment_name_from_file(__file__)
register_environment(CUSTOM_LOCO_MJX, get_config, create_env, GeneralProperties)

