from rl_x.algorithms.algorithm_manager import extract_algorithm_name_from_file, register_algorithm
from trust_region_irl.algorithms.near_ppo.flax_loco_mjx.near_ppo import NEAR_PPO
from trust_region_irl.algorithms.near_ppo.flax_loco_mjx.default_config import get_config
from trust_region_irl.algorithms.near_ppo.flax_loco_mjx.general_properties import GeneralProperties


NEAR_PPO_FLAX_LOCO_MJX = extract_algorithm_name_from_file(__file__)
register_algorithm(NEAR_PPO_FLAX_LOCO_MJX, get_config, NEAR_PPO, GeneralProperties)
